add typography scss
deriv-com/quill-ui pull request #2
Opened 2024-03-06 04:13 UTC by jia-deriv

2024-03-06 05:46 UTC, prince-deriv requested changes

2024-03-06 06:31 UTC, jia-deriv commented on lib/styles/quill.css
> +    --core-lineHeight-auto: normal;
Sure, will remove it

2024-03-11 05:17 UTC, Nuzhy-Deriv approved these changes

2024-03-11 07:51 UTC, prince-deriv approved these changes

2024-03-11 07:52 UTC, merged