Jia/_/storybook-enhancement
deriv-com/quill-ui pull request #216
Opened 2024-06-13 09:45 UTC by jia-deriv

2024-06-13 10:56 UTC, prince-deriv requested changes

2024-06-13 10:56 UTC, prince-deriv commented on lib/components/Link/link.stories.tsx
> +        // layout: "centered",
Can we remove instead?

2024-06-13 10:56 UTC, prince-deriv commented on lib/components/Tag/custom-tag.stories.tsx
> +            // },
let's remove this if not needed

2024-06-13 12:22 UTC, jia-deriv commented on lib/components/Link/link.stories.tsx
> +        // layout: "centered",
Sure

2024-06-13 12:23 UTC, jia-deriv commented on lib/components/Tag/custom-tag.stories.tsx
> +            // },
Sure

2024-06-19 06:29 UTC, prince-deriv approved these changes

2024-06-19 07:00 UTC, merged